<?php

/**
 * AYANE : ayane.co.jp
 * powered by NENE.
 *
 * PHP Version >= 8.4
 *
 * @package   AYANE
 * @author    hideyukiMORI <info@ayane.co.jp>
 * @copyright 2021 AYANE
 * @license   https://opensource.org/licenses/MIT MIT License
 * @link      https://ayane.co.jp/
 */

declare(strict_types=1);

namespace Nene\Xion;

/**
 * CLI command: regenerate docker/mysql/init/001_schema.sql from SchemaDefinition.
 *
 * Invoked by `cli/generateSchemaSql.php` (also aliased as `composer schema:generate`).
 *
 * The MySQL container's docker-entrypoint cannot run PHP, so the compiled DDL
 * must ship as a .sql file in the repo. This command is the canonical regenerator.
 * The DDL section is replaced in-place; the hand-written seed INSERT block below
 * the marker is preserved verbatim.
 */
class GenerateSchemaSqlCommand extends Command
{
    private const SCHEMA_PATH  = '/docker/mysql/init/001_schema.sql';
    private const SEED_MARKER  = '-- Sample seeds (hand-written; preserved across regeneration).';

    /**
     * @return array<string, 'none'|'optional'|'required'>
     */
    protected function optionDefinitions(): array
    {
        return ['check' => 'none'];
    }

    protected function helpText(): string
    {
        return <<<'TEXT'
Usage:
  php cli/generateSchemaSql.php [--check]

Options:
  --check  Compare generated content against the existing file and
           exit with status 1 if they differ (no file write). Used
           by the drift unit test.
  --help   Show this help.
TEXT;
    }

    /**
     * @param array<string, string|false> $options
     */
    protected function handle(array $options): int
    {
        $projectRoot = dirname(__DIR__, 2);
        $schemaPath  = $projectRoot . self::SCHEMA_PATH;

        $ddl = '';
        foreach (SchemaCompiler::mysqlStatements() as $statement) {
            $ddl .= $statement . ';' . PHP_EOL . PHP_EOL;
        }

        $existing = is_file($schemaPath) ? (string)file_get_contents($schemaPath) : '';
        $seeds    = '';
        if ($existing !== '' && str_contains($existing, self::SEED_MARKER)) {
            $seeds = substr($existing, (int)strpos($existing, self::SEED_MARKER));
        }

        $header = '-- AUTO-GENERATED by `composer schema:generate` (cli/generateSchemaSql.php).' . PHP_EOL
            . '-- Source of truth: class/xion/SchemaDefinition.php' . PHP_EOL
            . '-- Do not edit DDL by hand. Sample seeds below the marker stay hand-written.' . PHP_EOL . PHP_EOL;

        $body = $header . $ddl . ($seeds !== '' ? $seeds : (self::SEED_MARKER . PHP_EOL));

        if (isset($options['check'])) {
            if ($existing === $body) {
                $this->line('OK: docker/mysql/init/001_schema.sql matches generated output.');
                return 0;
            }
            $this->line('DRIFT: docker/mysql/init/001_schema.sql does not match generated output.');
            $this->line('Run `composer schema:generate` to refresh.');
            return 1;
        }

        file_put_contents($schemaPath, $body);
        $this->line('Wrote ' . $schemaPath);
        return 0;
    }
}
