#!/bin/sh

set -eu

mkdir -p ./data 2>/dev/null
mkdir -p ./data/uploads 2>/dev/null
mkdir -p ./view/config 2>/dev/null
mkdir -p ./view/compile 2>/dev/null
mkdir -p ./view/plugins 2>/dev/null
mkdir -p ./log 2>/dev/null

if id www-data >/dev/null 2>&1; then
    chown -R www-data:www-data ./data ./view/compile ./view/plugins ./log
fi

chmod 775 ./data ./data/uploads ./view/compile ./view/plugins ./log

# Write runtime PHP overrides driven by NENE_* env vars. The build-time
# zz-nene.ini (in docker/php/conf.d/) carries static values; this file
# is regenerated on every container start so operators can flip upload
# limits via compose env without rebuilding the image.
NENE_RUNTIME_INI=/usr/local/etc/php/conf.d/zz-nene-runtime.ini
if [ -w "$(dirname "$NENE_RUNTIME_INI")" ] || [ "$(id -u)" = "0" ]; then
    {
        echo "; Auto-generated by init.sh from NENE_* environment variables."
        echo "; Edit compose.yaml (or compose.prod.yaml) to change values."
        if [ -n "${NENE_UPLOAD_MAX_FILESIZE:-}" ]; then
            echo "upload_max_filesize = ${NENE_UPLOAD_MAX_FILESIZE}"
        fi
        if [ -n "${NENE_POST_MAX_SIZE:-}" ]; then
            echo "post_max_size = ${NENE_POST_MAX_SIZE}"
        fi
    } > "$NENE_RUNTIME_INI" 2>/dev/null || true
fi
