<?php

declare(strict_types=1);

/**
 * Regenerate `docker/mysql/init/001_schema.sql` from
 * {@see \Nene\Xion\SchemaDefinition} via {@see \Nene\Xion\SchemaCompiler}.
 *
 * The MySQL container's docker-entrypoint cannot run PHP, so the
 * compiled DDL must ship as a `.sql` file in the repo. This script is
 * the canonical regenerator. The DDL section is replaced in-place; the
 * hand-written seed `INSERT` block below the marker is preserved
 * verbatim.
 *
 * Usage:
 *   php cli/generateSchemaSql.php [--check]
 *
 * Options:
 *   --check  Compare generated content against the existing file and
 *            exit with status 1 if they differ (no file write). Used
 *            by the drift unit test.
 *   --help   Show this help.
 */

use Nene\Xion\SchemaCompiler;

require_once dirname(__DIR__) . '/vendor/autoload.php';

$options = getopt('', ['check', 'help']) ?: [];
if (isset($options['help'])) {
    echo <<<'TEXT'
Usage:
  php cli/generateSchemaSql.php [--check]

Options:
  --check  Compare without writing; exit 1 on drift.
  --help   Show this help.

TEXT;
    exit(0);
}

$projectRoot = dirname(__DIR__);
$schemaPath = $projectRoot . '/docker/mysql/init/001_schema.sql';
$seedMarker = '-- Sample seeds (hand-written; preserved across regeneration).';

$ddl = '';
foreach (SchemaCompiler::mysqlStatements() as $statement) {
    $ddl .= $statement . ';' . PHP_EOL . PHP_EOL;
}

$existing = is_file($schemaPath) ? (string)file_get_contents($schemaPath) : '';
$seeds = '';
if ($existing !== '' && str_contains($existing, $seedMarker)) {
    $seeds = substr($existing, (int)strpos($existing, $seedMarker));
}

$header = '-- AUTO-GENERATED by `composer schema:generate` (cli/generateSchemaSql.php).' . PHP_EOL
    . '-- Source of truth: class/xion/SchemaDefinition.php' . PHP_EOL
    . '-- Do not edit DDL by hand. Sample seeds below the marker stay hand-written.' . PHP_EOL . PHP_EOL;

$body = $header . $ddl . ($seeds !== '' ? $seeds : ($seedMarker . PHP_EOL));

if (isset($options['check'])) {
    if ($existing === $body) {
        echo "OK: docker/mysql/init/001_schema.sql matches generated output." . PHP_EOL;
        exit(0);
    }
    echo "DRIFT: docker/mysql/init/001_schema.sql does not match generated output." . PHP_EOL;
    echo "Run `composer schema:generate` to refresh." . PHP_EOL;
    exit(1);
}

file_put_contents($schemaPath, $body);
echo "Wrote " . $schemaPath . PHP_EOL;
