<?php

declare(strict_types=1);

/**
 * Compare a running database's schema against
 * {@see \Nene\Xion\SchemaDefinition} and emit the SQL that would
 * converge the live DB to the definition.
 *
 * **The CLI never applies SQL.** The operator pipes the output to a
 * file, reviews it, and runs `mysql` / `sqlite3` themselves. This is
 * the deliberate design from ADR-0009 (Option C): destructive ops stay
 * the operator's call, and rollback fantasies are not promoted.
 *
 * Scope (ADR-0009 initial):
 *
 * - Add table (`CREATE TABLE …`)
 * - Add column (`ALTER TABLE … ADD COLUMN …`)
 * - Add index (deferred to follow-up)
 *
 * Warnings on (operator hand-writes the SQL):
 *
 * - Drop table / drop column / drop index
 * - Column type change
 * - Column rename
 * - Constraint changes
 *
 * Usage:
 *
 *     # MySQL
 *     php cli/schemaDiff.php --dsn=mysql:host=127.0.0.1;port=3306;dbname=nene \
 *         --user=nene --pass=nene
 *
 *     # SQLite
 *     php cli/schemaDiff.php --dsn=sqlite:/var/www/html/data/nene.sqlite
 *
 * Options:
 *
 *   --dsn=…       PDO DSN (required).
 *   --user=…      Username (MySQL only).
 *   --pass=…      Password (MySQL only).
 *   --help        Show this help.
 *
 * Exit codes:
 *
 *   0  schema is in sync, OR diff was emitted successfully
 *   1  CLI usage error
 *   2  database connection / introspection error
 */

use Nene\Xion\SchemaDefinition;
use Nene\Xion\SchemaDiffer;

require_once dirname(__DIR__) . '/vendor/autoload.php';

/** @var array<string,string|bool> $options */
$options = getopt('', ['dsn:', 'user:', 'pass:', 'help']) ?: [];

if (isset($options['help'])) {
    fwrite(STDOUT, <<<HELP

NeNe schema-diff — operator-applied migration tool (ADR-0009).

USAGE
    php cli/schemaDiff.php --dsn=<pdo-dsn> [--user=<u>] [--pass=<p>]

    Or via composer:
    composer schema:diff -- --dsn=<pdo-dsn> [--user=<u>] [--pass=<p>]

OPTIONS
    --dsn=…       PDO DSN (required). MySQL or SQLite only.
    --user=…      Username (MySQL).
    --pass=…      Password (MySQL).
    --help        Show this help.

EXAMPLES
    # MySQL
    php cli/schemaDiff.php \\
        --dsn='mysql:host=127.0.0.1;port=3306;dbname=nene' \\
        --user=nene --pass=nene

    # SQLite
    php cli/schemaDiff.php --dsn='sqlite:/var/www/html/data/nene.sqlite'

    # Redirect for review-before-apply (recommended)
    composer schema:diff -- --dsn='mysql:...' --user=u --pass=p \\
        > migrations/\$(date +%F)-change.sql

OUTPUT
    stdout  the SQL to apply (review-then-pipe-to-mysql)
    stderr  annotations and warnings (not part of redirected SQL)

EXIT CODES
    0  schema is in sync OR diff emitted successfully
    1  CLI usage error (missing --dsn, unsupported driver)
    2  database connection / introspection error

NOT EMITTED (review-before-apply rule)
    The CLI never emits destructive SQL. Drops, column renames, type
    changes, constraint changes, and default-value-only changes are
    reported as stderr warnings only. Operators hand-write those.

SEE ALSO
    docs/development/schema-migrations.md
    docs/adr/0009-schema-migration-story.md
    composer schema:generate  (regenerate docker entrypoint snapshot)
    composer schema:check     (drift check vs snapshot)


HELP);
    exit(0);
}

$dsn = isset($options['dsn']) ? (string)$options['dsn'] : '';
if ($dsn === '') {
    fwrite(STDERR, "error: --dsn=… is required. Run `php cli/schemaDiff.php --help` for usage.\n");
    exit(1);
}

$user = isset($options['user']) ? (string)$options['user'] : null;
$pass = isset($options['pass']) ? (string)$options['pass'] : null;

try {
    $pdo = new PDO($dsn, $user, $pass, [
        PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
        PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
    ]);
} catch (PDOException $exception) {
    fwrite(STDERR, 'error: database connection failed: ' . $exception->getMessage() . "\n");
    exit(2);
}

$driver = $pdo->getAttribute(PDO::ATTR_DRIVER_NAME);
if ($driver !== SchemaDiffer::DRIVER_MYSQL && $driver !== SchemaDiffer::DRIVER_SQLITE) {
    fwrite(STDERR, "error: unsupported driver `$driver`. Supported: mysql, sqlite.\n");
    exit(1);
}

try {
    $live = introspect($pdo, $driver);
} catch (PDOException $exception) {
    fwrite(STDERR, 'error: schema introspection failed: ' . $exception->getMessage() . "\n");
    exit(2);
}

$diff = SchemaDiffer::diff($live, SchemaDefinition::tables(), $driver);

if ($diff['inSync']) {
    fwrite(STDERR, "-- schema is in sync with SchemaDefinition (driver=$driver)\n");
    foreach ($diff['warnings'] as $warning) {
        fwrite(STDERR, "-- warning: $warning\n");
    }
    exit(0);
}

fwrite(STDERR, "-- schema diff for driver=$driver (review before applying)\n");
foreach ($diff['warnings'] as $warning) {
    fwrite(STDERR, "-- warning: $warning\n");
}
fwrite(STDOUT, "-- generated by cli/schemaDiff.php (ADR-0009)\n");
fwrite(STDOUT, "-- driver: $driver\n");
fwrite(STDOUT, "-- review every statement before applying; this tool only emits add-only changes.\n");
foreach ($diff['newTables'] as $tableName => $sql) {
    fwrite(STDOUT, "\n-- new table: $tableName\n");
    fwrite(STDOUT, $sql . "\n");
}
foreach ($diff['newColumns'] as $entry) {
    fwrite(STDOUT, "\n-- new column: {$entry['table']}.{$entry['column']}\n");
    fwrite(STDOUT, $entry['sql'] . "\n");
}

exit(0);

/**
 * @return array<string,array<string,mixed>>
 */
function introspect(PDO $pdo, string $driver): array
{
    if ($driver === SchemaDiffer::DRIVER_SQLITE) {
        return introspectSqlite($pdo);
    }
    return introspectMysql($pdo);
}

/**
 * @return array<string,array<string,mixed>>
 */
function introspectMysql(PDO $pdo): array
{
    $database = (string)$pdo->query('SELECT DATABASE()')->fetchColumn();
    if ($database === '') {
        throw new RuntimeException('MySQL DSN did not specify a database (no DATABASE() in session).');
    }

    $tableStmt = $pdo->prepare(
        'SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES '
        . 'WHERE TABLE_SCHEMA = :schema AND TABLE_TYPE = "BASE TABLE"'
    );
    $tableStmt->execute([':schema' => $database]);
    /** @var array<int,string> $tables */
    $tables = $tableStmt->fetchAll(PDO::FETCH_COLUMN);

    $columnStmt = $pdo->prepare(
        'SELECT COLUMN_NAME, DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS '
        . 'WHERE TABLE_SCHEMA = :schema AND TABLE_NAME = :table'
    );

    $result = [];
    foreach ($tables as $table) {
        $columnStmt->execute([':schema' => $database, ':table' => $table]);
        $columns = [];
        foreach ($columnStmt->fetchAll() as $row) {
            $name = (string)$row['COLUMN_NAME'];
            $columns[$name] = ['data_type' => (string)$row['DATA_TYPE']];
        }
        $result[$table] = ['columns' => $columns];
    }
    return $result;
}

/**
 * @return array<string,array<string,mixed>>
 */
function introspectSqlite(PDO $pdo): array
{
    $tableStmt = $pdo->query('SELECT name FROM sqlite_master WHERE type = "table" AND name NOT LIKE "sqlite_%"');
    /** @var array<int,string> $tables */
    $tables = $tableStmt->fetchAll(PDO::FETCH_COLUMN);

    $result = [];
    foreach ($tables as $table) {
        $columnStmt = $pdo->query('PRAGMA table_info(' . $table . ')');
        $columns = [];
        foreach ($columnStmt->fetchAll() as $row) {
            $name = (string)$row['name'];
            $columns[$name] = ['data_type' => (string)$row['type']];
        }
        $result[$table] = ['columns' => $columns];
    }
    return $result;
}
