<?php

declare(strict_types=1);

namespace Nene\Tests\Unit\Xion;

use Nene\Xion\SchemaCompiler;
use Nene\Xion\SchemaDefinition;
use PHPUnit\Framework\TestCase;

/**
 * `SchemaCompiler` is the single-source emitter for both MySQL and SQLite
 * sample DDL. These tests pin its public surface and assert that the
 * hand-checked-in `docker/mysql/init/001_schema.sql` is byte-identical
 * to the compiler's MySQL output — the drift gate for ADR-0005.
 */
final class SchemaCompilerTest extends TestCase
{
    public function testTableListMatchesSchemaDefinition(): void
    {
        $mysqlCount = count(SchemaCompiler::mysqlStatements());
        $sqliteCount = count(SchemaCompiler::sqliteStatements());
        $defined = count(SchemaDefinition::tables());

        self::assertSame($defined, $mysqlCount);
        self::assertSame($defined, $sqliteCount);
    }

    public function testMysqlOutputCarriesEveryDefinedTable(): void
    {
        $mysql = implode("\n", SchemaCompiler::mysqlStatements());
        foreach (array_keys(SchemaDefinition::tables()) as $table) {
            self::assertStringContainsString('CREATE TABLE IF NOT EXISTS ' . $table, $mysql);
        }
    }

    public function testSqliteOutputCarriesEveryDefinedTable(): void
    {
        $sqlite = implode("\n", SchemaCompiler::sqliteStatements());
        foreach (array_keys(SchemaDefinition::tables()) as $table) {
            self::assertStringContainsString('CREATE TABLE IF NOT EXISTS ' . $table, $sqlite);
        }
    }

    public function testSqliteIndexStatementsExistForDeclaredIndexes(): void
    {
        $indexStatements = SchemaCompiler::sqliteIndexStatements();
        foreach (SchemaDefinition::tables() as $table) {
            foreach ($table['indexes'] ?? [] as $indexName => $columns) {
                $matched = false;
                foreach ($indexStatements as $statement) {
                    if (str_contains($statement, 'CREATE INDEX IF NOT EXISTS ' . $indexName . ' ')) {
                        $matched = true;
                        break;
                    }
                }
                self::assertTrue(
                    $matched,
                    'SQLite index ' . $indexName . ' was not emitted by SchemaCompiler.'
                );
            }
        }
    }

    public function testSqliteTriggersExistForEveryDatetimeTouchColumn(): void
    {
        $triggerStatements = SchemaCompiler::sqliteTriggerStatements();
        foreach (SchemaDefinition::tables() as $tableName => $table) {
            foreach ($table['columns'] ?? [] as $columnName => $column) {
                if (($column['type'] ?? '') !== 'datetime-touch') {
                    continue;
                }
                $expected = $tableName . '_' . $columnName . '_trigger';
                $matched = false;
                foreach ($triggerStatements as $statement) {
                    if (str_contains($statement, 'CREATE TRIGGER IF NOT EXISTS ' . $expected)) {
                        $matched = true;
                        break;
                    }
                }
                self::assertTrue($matched, 'Missing SQLite trigger ' . $expected);
            }
        }
    }

    /**
     * Drift gate for ADR-0005: the committed `docker/mysql/init/001_schema.sql`
     * DDL section must equal the compiler's MySQL output. The hand-written
     * seed section below the marker is allowed to differ and is not checked
     * here (separate concern).
     */
    public function testDockerInitSqlMatchesCompiledOutput(): void
    {
        $repoRoot = dirname(__DIR__, 3);
        $sqlPath = $repoRoot . '/docker/mysql/init/001_schema.sql';
        self::assertFileExists($sqlPath);

        $contents = (string)file_get_contents($sqlPath);
        $marker = '-- Sample seeds (hand-written; preserved across regeneration).';
        $markerPos = strpos($contents, $marker);
        self::assertNotFalse(
            $markerPos,
            'docker/mysql/init/001_schema.sql is missing the seed marker. Run `composer schema:generate`.'
        );

        $ddlSection = substr($contents, 0, (int)$markerPos);

        $expectedHeader = '-- AUTO-GENERATED by `composer schema:generate` (cli/generateSchemaSql.php).' . "\n"
            . '-- Source of truth: class/xion/SchemaDefinition.php' . "\n"
            . '-- Do not edit DDL by hand. Sample seeds below the marker stay hand-written.' . "\n\n";

        $expectedDdl = '';
        foreach (SchemaCompiler::mysqlStatements() as $statement) {
            $expectedDdl .= $statement . ';' . "\n\n";
        }

        self::assertSame(
            $expectedHeader . $expectedDdl,
            $ddlSection,
            'DDL section of docker/mysql/init/001_schema.sql does not match SchemaCompiler::mysqlStatements(). '
                . 'Run `composer schema:generate` to refresh.'
        );
    }
}
