#!/usr/bin/env bash
#
# Bootstrap a new NeNe field trial clone.
#
# Usage:
#   tools/nene-ft-new.sh <topic-kebab>
#
# Example:
#   tools/nene-ft-new.sh smarty-html
#
# What it does:
#   1. Auto-detects the next FT number from existing clones under $NENE_FT_ROOT
#      (default: ../NeNe-FT/ relative to this framework checkout).
#   2. `git clone` this framework into ../NeNe-FT/ft{N}-{topic}/ so the trial
#      starts from the local HEAD (not origin/main) — useful when the framework
#      has unmerged feature branches you want the trial to exercise.
#   3. Writes a per-clone .env that offsets host ports so the clone can run
#      alongside the framework (app=8080+N, mysql=3307+N).
#   4. Drops .claude/settings.local.json with the FT autonomy permissions, so
#      Claude Code launched from inside the clone does not stop at every
#      composer/docker/gh/git command.
#   5. Writes an FT{N}-PLAN.md skeleton matching the trial conventions in
#      docs/field-trials/README.md.
#
# Nothing in the clone is committed back to the framework repository except
# the final field-trial report at the end of the trial.

set -euo pipefail

usage() {
    cat >&2 <<'USAGE'
Usage: tools/nene-ft-new.sh <topic-kebab>

Creates a fresh trial clone under $NENE_FT_ROOT (defaults to ../NeNe-FT/)
with a unique port offset, .claude permissions, and a PLAN skeleton.

Examples:
  tools/nene-ft-new.sh smarty-html
  NENE_FT_ROOT=/tmp/ft tools/nene-ft-new.sh openapi-authoring
USAGE
    exit 1
}

[ $# -eq 1 ] || usage
case "$1" in
    -h|--help|help) usage ;;
esac

TOPIC="$1"
if ! printf '%s' "$TOPIC" | grep -qE '^[a-z0-9]([a-z0-9-]*[a-z0-9])?$'; then
    echo "ERROR: topic must be kebab-case (lowercase a-z 0-9 with internal dashes): '$TOPIC'" >&2
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
FRAMEWORK_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
FT_ROOT="${NENE_FT_ROOT:-$FRAMEWORK_ROOT/../NeNe-FT}"

mkdir -p "$FT_ROOT"

LAST_N=$(ls -1 "$FT_ROOT" 2>/dev/null \
    | sed -nE 's/^ft([0-9]+)-.*/\1/p' \
    | sort -n \
    | tail -1)
LAST_N="${LAST_N:-0}"
N=$((LAST_N + 1))

CLONE_DIR="$FT_ROOT/ft${N}-${TOPIC}"
if [ -e "$CLONE_DIR" ]; then
    echo "ERROR: $CLONE_DIR already exists" >&2
    exit 1
fi

PORT_APP=$((8080 + N))
PORT_MYSQL=$((3307 + N))
HEAD_SHA="$(git -C "$FRAMEWORK_ROOT" rev-parse --short HEAD)"

echo "==> Cloning framework ($HEAD_SHA) into $CLONE_DIR"
git clone --quiet "$FRAMEWORK_ROOT" "$CLONE_DIR"

cd "$CLONE_DIR"

echo "==> Writing .env (app=$PORT_APP, mysql=$PORT_MYSQL)"
cat > .env <<EOF
# Auto-generated by tools/nene-ft-new.sh for FT${N}.
# Host port offsets so this clone can run alongside the framework or other FT clones.
NENE_PORT=${PORT_APP}
NENE_MYSQL_PORT=${PORT_MYSQL}
EOF

echo "==> Writing .claude/settings.local.json"
mkdir -p .claude
cat > .claude/settings.local.json <<'EOF'
{
  "permissions": {
    "allow": [
      "Bash(composer *)",
      "Bash(docker compose *)",
      "Bash(docker ps)",
      "Bash(docker ps *)",
      "Bash(docker logs *)",
      "Bash(docker exec *)",
      "Bash(vendor/bin/phpunit *)",
      "Bash(./vendor/bin/phpunit *)",
      "Bash(php *)",
      "Bash(curl *)",
      "Bash(git *)",
      "Bash(gh *)",
      "Bash(jq *)",
      "Bash(ls)",
      "Bash(ls *)",
      "Bash(find . *)",
      "Bash(find /home/xi/github *)",
      "Bash(grep *)",
      "Bash(rg *)",
      "Bash(wc *)",
      "Bash(awk *)",
      "Bash(sed -n *)",
      "Bash(cat *)",
      "Bash(head *)",
      "Bash(tail *)",
      "Bash(echo *)",
      "Bash(printf *)",
      "Bash(date)",
      "Bash(date *)",
      "Bash(mkdir *)",
      "Bash(cp *)",
      "Bash(mv *)",
      "Bash(touch *)",
      "Bash(test *)",
      "Bash(true)",
      "Bash(false)",
      "Read",
      "Skill"
    ],
    "deny": [
      "Bash(rm -rf /*)",
      "Bash(sudo *)",
      "Bash(git push --force*)"
    ]
  }
}
EOF

echo "==> Writing FT${N}-PLAN.md skeleton"
cat > "FT${N}-PLAN.md" <<EOF
# FT${N} — ${TOPIC}: Plan

Working note inside the trial clone. Not committed back to the framework repository. Final report will live at \`docs/field-trials/$(date +%Y-%m)-field-trial-${N}.md\` in the framework repo after the trial ends.

Methodology: \`../../NeNe/docs/field-trials/README.md\`. Trial Issue: (file one and link here)

## Baseline

- NeNe ref: \`${HEAD_SHA}\`
- Clone path: \`${CLONE_DIR}\`
- Host ports: app=${PORT_APP}, mysql=${PORT_MYSQL}
- PHP: 8.4.x (in container)
- Database: MySQL 8.4 (Docker Compose default), SQLite parity via \`cli/initSQLite.php\`

### Baseline verification (fill in after first run)

| Check | Result |
| --- | --- |
| \`docker compose run --rm app composer install\` | |
| \`docker compose up -d app\` + \`/health\` | |
| \`composer test\` | |
| \`NENE_HTTP_BASE_URL=http://127.0.0.1:${PORT_APP} composer test:http\` | |

## Goal

(Describe the surface FT${N} exercises that previous trials skipped.)

## Expected friction surfaces

| # | Hypothesis | Likely kind |
| --- | --- | --- |
| H-A | | docs-gap / feature-gap / design-trade-off |

## Implementation Phases

1. Baseline confirmed.
2. ...

## Operating Notes

- All commands via \`docker compose exec -T app ...\` from this clone.
- Trial clone is independent; nothing committed back to framework except the final FT${N} report.
EOF

cat <<EOF

==> Done.

Trial directory: $CLONE_DIR

Next steps:
  cd $CLONE_DIR
  docker compose up -d app
  curl -s http://127.0.0.1:${PORT_APP}/health/index | jq .Data.healthStatus

  # File a tracking Issue:
  gh issue create --title "FT${N}: ${TOPIC}" --body "..."

  # When the trial ends, write the report at:
  $FRAMEWORK_ROOT/docs/field-trials/$(date +%Y-%m)-field-trial-${N}.md
EOF
